# Run from the repository root after retrieving the unmodified source archive.
# The archive and original code are not redistributed with this package.
source('research/raw/CATBUB/extracted/CATBUBDesign/CATBUB-Design.R')
# Tighten integration for the numerical comparison fixture only.
integrate <- function(...) stats::integrate(..., rel.tol=1e-11, subdivisions=2000)
cases <- list(
 list(X=rbind(c(25,15,10),c(30,15,5)), U=c(100,50,0)),
 list(X=rbind(c(0,0,0),c(0,0,0)), U=c(100,20,0)),
 list(X=rbind(c(3,7),c(8,2)), U=c(0,100)),
 list(X=rbind(c(0,1,0,0),c(0,0,1,0)), U=c(0,35,70,100)),
 list(X=rbind(c(1000,300,50),c(900,400,50)), U=c(100,50,0)))
results <- t(vapply(cases, function(z) unlist(pmu.diff.test(z$X,z$U,method='Beta')), numeric(2)))
write.table(results, 'tests/fixtures/catbub-reference.csv', sep=',', row.names=FALSE, col.names=TRUE)
# Capture data generated by an unchanged source design call. This permits
# deterministic comparison independent of R versus NumPy random streams.
rm(integrate)
original_generation <- gen.seq.data
captured <- list()
gen.seq.data <- function(...) {
 result <- original_generation(...)
 captured[[length(captured)+1]] <<- result
 result
}
set.seed(9703)
result <- catbub.design(array(c(.4,.7,.6,.3), c(1,2,2)), c(.5,1), c(100,0),
                       eps=.15, Gs=c(250,250))
rows <- do.call(rbind, lapply(seq_along(captured), function(i) {
 do.call(rbind, lapply(seq_along(captured[[i]]), function(j) {
  x <- captured[[i]][[j]]
  c(i,j,as.vector(t(x)),unlist(pmu.diff.test(x,c(100,0),method='Beta')))
 }))
}))
write.table(rows,'research/raw/CATBUB/common-trials.csv',sep=',',row.names=FALSE,col.names=FALSE)
capture.output(result, file='research/raw/CATBUB/design-result.txt')
print(result)
